spring:
  application:
    name: order

  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
profiles: dev90
